function object_struct=InitializeObjectStruct()
object_struct = struct(...
    'group_type',{}, ... %1 represents tube_group and 0 represents hybrid group
    'groupId', {}, ...
    'memberId', {}, ...
    'member_type', {}, ... %1 represents tube and 0 represents frame
    'start_time', {}, ...
    'duration', {}, ...
    'memberNum', {});
end